(******************************************************************************)
(*                                                                            *)
(*              January 6: Capitol Breach Event Chronology                    *)
(*                                                                            *)
(*     Formalizes the Capitol breach (January 6, 2021): 140+ officer injury   *)
(*     records, tunnel crush timeline, seditious conspiracy convictions       *)
(*     (Rhodes 18y, Tarrio 22y), electoral certification interruption, and    *)
(*     National Guard deployment authority chain. Models Vice Presidential    *)
(*     certification role per 12th Amendment and 3 U.S.C. § 15.               *)
(*                                                                            *)
(*     "I defended this satisfactorily at trial to twelve American citizens   *)
(*     who unanimously found otherwise."                                      *)
(*     - Federal jury, United States v. Rhodes, 2022                          *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 7, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
